### ISSUE TITLE
Tìm hiểu về useState(), useEffect(), useRef() 

### ISSUE THREAD

**Issue by PhamNguyenNhutTruong** [PhamNguyenNhutTruong/Nhom2_CCPTPM#10]
Nhiệm vụ của ngày mai là các bạn sẽ tìm hiểu về một số Hooks thường được sử dụng trong ReactJs

**Comment by anhhoang29** [comment]
useState(): Hàm này nhận đầu vào là giá trị khởi tạo của 1 state và trả ra 1 mảng gồm có 2 phần tử, phần tử đầu tiên là state hiện tại, phần tử thứ 2 là 1 function dùng để update state
useEffect(): Nó giúp chúng ta xử lý các side effects, useEffect sẽ tương tự với các hàm componentDidMount, componentDidUpdate và componentWillUnMount trong LifeCycle khi khai báo arrayDependencies là []
userRef(): cho phép bạn duy trì các giá trị giữa các lần hiển thị

**Comment by hautran-02** [comment]
- **useState():** Hàm này nhận đầu vào là giá trị khởi tạo của 1 state và trả ra 1 mảng gồm có 2 phần tử, phần tử đầu tiên là state hiện tại, phần tử thứ 2 là 1 function dùng để update state
- **useEffect():** Nó giúp chúng ta xử lý các side effects, useEffect sẽ tương tự với các hàm componentDidMount, componentDidUpdate và componentWillUnMount trong LifeCycle khi khai báo arrayDependencies là []
- **userRef():** cho phép bạn duy trì các giá trị giữa các lần hiển thị

**Comment by PhamNguyenNhutTruong** [comment]
1. useState(): hook này cho phép ta lưu trữ và cập nhật state của component. useState() nhận vào giá trị khởi tạo của state và trả về một mảng chứa state hiện tại và một hàm để cập nhật state mới. Khi gọi hàm cập nhật state này, React sẽ tự động render lại component để hiển thị state mới.
2. useEffect(): hook này cho phép ta thực hiện các side effect như gọi API, thay đổi DOM, cập nhật state, ... trong component. useEffect() nhận vào một hàm và một mảng dependency, và sẽ được gọi sau mỗi lần render component. Nếu mảng dependency được truyền vào thì useEffect() sẽ chỉ thực hiện khi một trong các giá trị trong mảng thay đổi.
3. useRef(): hook này cho phép ta tạo một tham chiếu đến một element trong DOM hoặc một giá trị bất kỳ. useRef() sẽ trả về một đối tượng với thuộc tính .current chứa giá trị của tham chiếu đó.
