### ISSUE TITLE
Lập danh sách các chức năng mới cho project

### ISSUE THREAD

**Issue by PhamNguyenNhutTruong** [PhamNguyenNhutTruong/Nhom2_CCPTPM#12]
Mọi người tìm hiểu trước 5 chức năng mà chúng ta có thể phát triển thêm cho dự án của nhóm mình.

**Comment by PhamNguyenNhutTruong** [comment]
Tui có một ý tưởng đó là tạo Shortcut và hỗ trợ tách âm thanh video gốc và chèn thêm nhạc mới

**Comment by anhhoang29** [comment]
- chèn nhạc cho video

**Comment by hautran-02** [comment]
Chức năng gắn filter cho video

**Comment by anhhoang29** [comment]
làm chức năng tua nhanh video
