### ISSUE TITLE
Vẽ class Diagram cho hệ thống

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#17]
- [x] Tìm hiểu khái niệm class diagram 
- [x] vẽ class diagram

**Comment by hautran-02** [comment]
Kết quả:
https://docs.google.com/document/d/1DJW0RK6LX148p961x4L0vwxAiJvdp0wB81udB32DW20/edit

**Comment by anhhoang29** [comment]
![image](https://user-images.githubusercontent.com/93761101/229297856-77121da7-dd3b-489e-8c4e-418f13e6ba82.png)
