### ISSUE TITLE
Tìm hiểu và thực thi docker vào project

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#19]
- [x] Tổng quan về docker

- [x] Thực thi docker vào project

**Comment by anhhoang29** [comment]
Docker là một nền tảng phần mềm được sử dụng để xây dựng, đóng gói và chạy các ứng dụng trong các môi trường độc lập với hệ điều hành. Nó cho phép các ứng dụng được đóng gói và vận chuyển dễ dàng và đáng tin cậy, đồng thời giúp giảm thiểu sự khác biệt giữa các môi trường và giúp đơn giản hóa quá trình phát triển và triển khai ứng dụng. Docker sử dụng công nghệ container để đóng gói các ứng dụng và các thành phần liên quan của chúng, bao gồm các thư viện, tệp cấu hình và các công cụ hệ thống cần thiết, tạo ra một môi trường độc lập và cô lập.
Install docker 
![image](https://user-images.githubusercontent.com/93761101/227785384-ba765e69-387c-4b49-83ab-b8fd6554ef4f.png)

Docker bao gồm các thành phần chính sau:

Docker Engine: Là thành phần chính của Docker, cung cấp các công cụ để quản lý và chạy các container Docker.

Docker Hub: Là một kho lưu trữ trực tuyến được cung cấp bởi Docker để chia sẻ các container, hình ảnh Docker và các tệp Dockerfile.

Docker Compose: Là công cụ để định nghĩa và chạy các ứng dụng phức tạp đơn giản hóa quá trình triển khai.

Docker Swarm: Là một công cụ quản lý cluster Docker, cho phép triển khai các ứng dụng trên nhiều máy chủ và quản lý chúng dưới dạng một đơn vị.

Docker CLI: Cung cấp các lệnh để quản lý các container Docker, tạo hình ảnh Docker và các tệp Dockerfile.

Ngoài ra, Docker cũng có thể tích hợp với các công nghệ như Kubernetes, để quản lý các ứng dụng phân tán và các hệ thống lớn hơn.

**Comment by hautran-02** [comment]
Docker là một nền tảng mở để phát triển, vận chuyển và chạy các ứng dụng. Docker cho phép bạn tách các ứng dụng của mình khỏi cơ sở hạ tầng để bạn có thể phân phối phần mềm một cách nhanh chóng. Với Docker, bạn có thể quản lý cơ sở hạ tầng của mình giống như cách bạn quản lý các ứng dụng của mình. Bằng cách tận dụng các phương pháp của Docker để vận chuyển, thử nghiệm và triển khai mã một cách nhanh chóng, bạn có thể giảm đáng kể độ trễ giữa viết mã và chạy mã trong sản xuất.
Docker bao gồm các thành phần chính sau:
- Container là một quy trình được đóng hộp cát trên máy của bạn, quy trình này được tách biệt khỏi tất cả các quy trình khác trên máy chủ. Sự cô lập đó tận dụng các không gian tên kernel và cgroups, những tính năng đã có trong Linux từ lâu. Docker đã làm việc để làm cho những khả năng này trở nên dễ tiếp cận và dễ sử dụng.
- Docker Engine: Là thành phần chính của Docker, cung cấp các công cụ để quản lý và chạy các container Docker.
- Docker Hub: Là một kho lưu trữ trực tuyến được cung cấp bởi Docker để chia sẻ các container, hình ảnh Docker và các tệp Dockerfile.
- Docker Compose: Là công cụ để định nghĩa và chạy các ứng dụng phức tạp đơn giản hóa quá trình triển khai.
- Docker Swarm: Là một công cụ quản lý cluster Docker, cho phép triển khai các ứng dụng trên nhiều máy chủ và quản lý chúng dưới dạng một đơn vị.
- Docker CLI: Cung cấp các lệnh để quản lý các container Docker, tạo hình ảnh Docker và các tệp Dockerfile.

**Comment by PhamNguyenNhutTruong** [comment]
Docker là một nền tảng mã nguồn mở cho phép bạn đóng gói và chạy ứng dụng trong các container. Các container là một cách để gói ứng dụng và các thành phần phụ thuộc của nó thành một gói duy nhất, độc lập với hệ điều hành và phần cứng của máy tính. Điều này giúp cho việc triển khai và chạy ứng dụng trên các môi trường khác nhau trở nên đơn giản hơn, từ việc phát triển trên máy tính đến triển khai trên các máy chủ hoặc cloud.

Điểm mạnh của Docker là nó cho phép bạn triển khai các ứng dụng trên bất kỳ môi trường nào có Docker được cài đặt, giảm thiểu sự phụ thuộc vào hệ thống và phần cứng của máy tính. Ngoài ra, Docker cũng cung cấp cho người dùng các tính năng như khả năng tạo và quản lý các container, tự động triển khai các ứng dụng, cũng như cung cấp các công cụ cho việc quản lý các ứng dụng và container.

Sử dụng Docker cũng giúp cho việc phát triển phần mềm trở nên đơn giản hơn, vì bạn có thể đóng gói các ứng dụng vào các container và chia sẻ chúng với đồng nghiệp một cách dễ dàng, giúp cho việc phát triển và kiểm thử trở nên hiệu quả hơn.

Trong tổng quan, Docker là một công nghệ rất hữu ích cho việc triển khai và quản lý các ứng dụng trên nhiều môi trường khác nhau, và nó đang được sử dụng rộng rãi bởi các nhà phát triển và doanh nghiệp trên toàn thế giới.
Ngoài các ưu điểm đã nêu ở trên, Docker còn có một số lợi ích khác như:

Tiết kiệm chi phí: Docker giúp giảm thiểu chi phí cho việc phát triển và triển khai ứng dụng, vì bạn chỉ cần đóng gói ứng dụng vào container và chia sẻ nó với đồng nghiệp một cách dễ dàng, giảm thiểu chi phí cho việc mua sắm phần cứng và cài đặt hệ thống.

Tính di động: Docker cho phép bạn đóng gói ứng dụng và các thành phần phụ thuộc của nó vào một container, giúp cho việc chuyển đổi ứng dụng từ một môi trường sang một môi trường khác trở nên dễ dàng hơn.

Tính linh hoạt: Docker cho phép bạn tạo và quản lý các container một cách dễ dàng, giúp cho việc triển khai và chạy ứng dụng trên các môi trường khác nhau trở nên linh hoạt hơn.

Tăng hiệu suất: Docker giúp tăng hiệu suất cho ứng dụng bằng cách giúp ứng dụng chạy trên các container độc lập với nhau, giúp cho các ứng dụng có thể chạy trên các hệ thống tập trung mà không ảnh hưởng đến hiệu suất.

Bảo mật: Docker cung cấp các tính năng bảo mật như cơ chế isolation và các công cụ quản lý, giúp cho việc bảo mật dữ liệu và ứng dụng trở nên an toàn hơn.

Tóm lại, Docker là một công nghệ đang được sử dụng rộng rãi trong việc phát triển và triển khai các ứng dụng trên nhiều môi trường khác nhau, giúp cho việc phát triển và triển khai ứng dụng trở nên đơn giản, hiệu quả và an toàn hơn.
![image](https://user-images.githubusercontent.com/89334096/227785790-ed7647de-5f01-41a5-83d4-6396a2318dda.png)

**Comment by hautran-02** [comment]
Kết quả run docker:
![image](https://user-images.githubusercontent.com/110884738/230898439-6c58b944-0c92-4d7c-bc51-94581b2e9486.png)
Container
![image](https://user-images.githubusercontent.com/110884738/230898472-1ccc9434-f71a-4f8e-9a55-8d413f8fabca.png)
Image:
![image](https://user-images.githubusercontent.com/110884738/230898489-65bf4044-2e4d-40ad-8892-7b3d255da1d2.png)
