### ISSUE TITLE
Viết mô tả, readme cho dự án.

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#20]
- [x] Viết readme mới cho project
- [x] Viết mô tả cho project

**Comment by anhhoang29** [comment]
Viết readme cho dự án
![image](https://user-images.githubusercontent.com/93761101/227998828-97bf39d3-1d07-4f70-8b9e-010cd17f0c2e.png)
 Mô tả đồ án
Đầu tiên để có thể hoàn thành tốt đề tài cần phải nắm vững kiến thức, công nghệ sử dụng,
cụ thể ở đây là cần hiểu rõ hoạt động và có thể sử dụng .NET 5.0 để xây dựng web API,
dùng ReactJS xây dựng giao diện thân thiện với người dùng, và cơ sở dữ liệu MongoDB
để lưu trữ dữ liệu. Sau đó áp dụng kiến thức đã được tìm hiểu để xây dựng trang web giúp
phân tích, xử lý video về các giải đấu bóng đá.

**Comment by hautran-02** [comment]
Cách run Front-End:
![image](https://user-images.githubusercontent.com/110884738/227999345-bf5b36ba-12c8-4a4b-9cdd-af3c68e817ab.png)

**Comment by PhamNguyenNhutTruong** [comment]
![image](https://user-images.githubusercontent.com/89334096/227999504-d24aea4d-4599-45f9-9a61-72cb618dd3b1.png)
![image](https://user-images.githubusercontent.com/89334096/227999590-0fbaa242-e733-4c20-92d5-fe13799ff324.png)
