### ISSUE TITLE
Vẽ usecase chức năng Đăng ký, đăng nhập, đăng xuất, thêm trận đấu, xóa trận đấu, upload file json cho cho trận đấu

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#21]
- [x] Đăng ký, đăng nhập

- [x] đăng xuất, thêm trận đấu

- [x] xóa trận đấu, upload file json cho cho trận đấu

**Comment by PhamNguyenNhutTruong** [comment]
![image](https://user-images.githubusercontent.com/89334096/228282012-3a1c420b-8ec5-417f-ab44-e4bab8c728a1.png)
![image](https://user-images.githubusercontent.com/89334096/228282117-d2e2aef8-e733-4351-aaa8-53d6149b066d.png)

**Comment by anhhoang29** [comment]
![image](https://user-images.githubusercontent.com/93761101/228504180-b1495708-b478-489f-ae0f-9e246093850e.png)


![image](https://user-images.githubusercontent.com/93761101/228504021-ca74febc-5899-4f71-a939-8feae5227876.png)

**Comment by hautran-02** [comment]
Use case
- Đăng nhập:
![image](https://user-images.githubusercontent.com/110884738/228572269-5b0075ff-9736-4973-a705-6c6d77f20e47.png)
- Đăng ký:
![image](https://user-images.githubusercontent.com/110884738/228572374-9d2c0566-7a02-435a-901d-10ec516044ff.png)

**Comment by PhamNguyenNhutTruong** [comment]
Ok hoàn thành task này
