### ISSUE TITLE
Vẽ use case chức năng lọc thông tin trận đấu, tìm kiếm trận trận đấu, xử lý đánh dấu để cắt ghép video, upload hình ảnh và video, thêm hình ảnh vào video, thêm video khi xử lý video

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#22]
- [x] chức năng lọc thông tin trận đấu, tìm kiếm trận trận đấu
- [x] xử lý đánh dấu để cắt ghép video, upload hình ảnh và video
- [x] thêm hình ảnh vào video, thêm video khi xử lý video

**Comment by anhhoang29** [comment]
![image](https://user-images.githubusercontent.com/93761101/228524811-c4052f13-d332-4381-adb7-0e83a46cf344.png)

![image](https://user-images.githubusercontent.com/93761101/228530700-6a533603-d3a1-41fc-a1fa-a093cdfd7917.png)

**Comment by PhamNguyenNhutTruong** [comment]
![image](https://user-images.githubusercontent.com/89334096/228567405-fed14f97-158e-47a8-a73b-400b02aef050.png)
![image](https://user-images.githubusercontent.com/89334096/228567448-15c078ac-a7f9-4791-adee-70e790f518d1.png)

**Comment by hautran-02** [comment]
Lọc trận đấu:
![image](https://user-images.githubusercontent.com/110884738/228574085-b9d51844-35d3-4e97-b381-4a517136e1c3.png)
Tìm kiếm trận đấu:
![image](https://user-images.githubusercontent.com/110884738/228574354-cbec56f3-710f-4214-b4bb-3ee1d1faa903.png)

**Comment by PhamNguyenNhutTruong** [comment]
ok hoàn thành task này
