### ISSUE TITLE
Vẽ use case lọc và tìm kiếm video, download video, chia sẻ video

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#23]
- [x] lọc và tìm kiếm video
- [x] download video
- [x]  chia sẻ video

**Comment by hautran-02** [comment]
Chức năng Lọc và tìm kiếm video
https://docs.google.com/document/d/1bLqTVQjIKMlLp5pSUSyR3uyjaUdOckmYXTcYbyqqdvs/edit

**Comment by PhamNguyenNhutTruong** [comment]
![image](https://user-images.githubusercontent.com/89334096/228878546-c50c8791-8f9a-4e5a-a86b-f092f3b1555c.png)

**Comment by hautran-02** [comment]
Lọc thông tin trận đấu:
![image](https://user-images.githubusercontent.com/110884738/229027765-a4a32f29-3dbd-430d-ad1f-c048ddd1f40b.png)
Tìm kiếm video:
![image](https://user-images.githubusercontent.com/110884738/229027765-a4a32f29-3dbd-430d-ad1f-c048ddd1f40b.png)
