### ISSUE TITLE
Thực hiện thiết kế nội dung document theo tài liệu có sẵn

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#24]
Dựa vào template hoàn thành nội dung:
[https://docs.google.com/document/d/1Bm-KBJYcuVtZBBBlmW-MMjpFt9eAsZJW/edit?usp=sharing&ouid=100081216597459798773&rtpof=true&sd=true](url)

**Comment by hautran-02** [comment]
Phần Introduce:
https://docs.google.com/document/d/13hCPNRMqTYwwLKfQQTe0MB-cSpmr-0oK/edit?usp=sharing&ouid=106936540166735392004&rtpof=true&sd=true

**Comment by PhamNguyenNhutTruong** [comment]
Đã hoàn thành phần 3 của tài liệu
![image](https://user-images.githubusercontent.com/89334096/229323992-53bf03fe-8a0f-465b-81a3-c414941d631c.png)
![image](https://user-images.githubusercontent.com/89334096/229324000-efea7e2f-6db2-4786-b692-e7b0bc7d03ee.png)
![image](https://user-images.githubusercontent.com/89334096/229324014-56187452-2d8d-41c2-918f-d918a7b2d64c.png)
...
