### ISSUE TITLE
Mô tả lại UI cho Project 

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#25]
- [x] Đăng ký, đăng nhập, đăng xuất, thêm trận đấu, xóa trận đấu

- [x]  upload file json cho cho trận đấu, chức năng lọc thông tin trận đấu, tìm kiếm trận trận đấu, xử lý đánh dấu để cắt ghép video, upload hình ảnh và video

- [x] xóa hình ảnh video, thêm hình ảnh vào video, thêm video khi xử lý video, lọc và tìm kiếm video, download video, chia sẻ video

**Comment by PhamNguyenNhutTruong** [comment]
![image](https://user-images.githubusercontent.com/89334096/229271202-e759417b-185a-42da-88c4-b0547cc14b8f.png)
![image](https://user-images.githubusercontent.com/89334096/229271219-883c15b2-6264-4dd6-b282-624824c79efc.png)
![image](https://user-images.githubusercontent.com/89334096/229271231-6c4379b6-2689-430e-98e9-16eca5aa2568.png)
![image](https://user-images.githubusercontent.com/89334096/229271237-2c8a32f4-ebdc-4d54-bd69-417080afb1dd.png)
![image](https://user-images.githubusercontent.com/89334096/229271255-44a1a085-2933-488d-b86f-e3f9d2e43f03.png)
![image](https://user-images.githubusercontent.com/89334096/229271270-85c0ee88-3cbc-4f7e-b290-7a2d88c66dc4.png)
![image](https://user-images.githubusercontent.com/89334096/229271280-05525441-61b1-49e0-aac9-254a2309ca72.png)

**Comment by hautran-02** [comment]
Đăng nhập:
![image](https://user-images.githubusercontent.com/110884738/229293467-168902d5-a357-410c-878c-f60b3ad2440d.png)
![image](https://user-images.githubusercontent.com/110884738/229293460-1b4d374f-2c9d-45e3-83a0-6e0cd04d23ec.png)
Đăng ký:
![image](https://user-images.githubusercontent.com/110884738/229293493-92aea282-a06a-4410-b1f4-c1e2c79fc0c2.png)
![image](https://user-images.githubusercontent.com/110884738/229293504-5d75b2b7-09e4-44ab-8da7-bd04dfbca198.png)

Thêm trận đấu:

Xóa trận đấu:

**Comment by anhhoang29** [comment]
Upload file Json cho trận đấu
  
![image](https://user-images.githubusercontent.com/93761101/229381060-fe828890-8ea0-4e8d-a705-55f28476b1d7.png)
![image](https://user-images.githubusercontent.com/93761101/229381065-4a314e40-6ff3-4726-b3c4-3f724a18d6cd.png)

 
Lọc thông tin trận đấu
 
 
![image](https://user-images.githubusercontent.com/93761101/229381074-a73f9054-8e59-4008-a8d6-2a3550b24462.png)
![image](https://user-images.githubusercontent.com/93761101/229381081-cf9c398e-90ca-4c30-aace-f9f2c6209407.png)

Chức năng tìm kiếm trận đấu
 
 
![image](https://user-images.githubusercontent.com/93761101/229381087-c8b39a87-1757-4974-ab0b-74afa71332a9.png)
![image](https://user-images.githubusercontent.com/93761101/229381091-3038d3cb-e8ce-44f6-9c49-c2add6bfc53c.png)


Chức năng xử lý đánh dấu để cắt ghép
 
![image](https://user-images.githubusercontent.com/93761101/229381097-a44dcea6-22fb-4f23-ac1c-2e5b4e223121.png)
![image](https://user-images.githubusercontent.com/93761101/229381101-81ad148b-9774-441a-9390-f0ecdf28b63c.png)

 
Upload hình ảnh và video
 
![image](https://user-images.githubusercontent.com/93761101/229381108-6eefca13-df2c-439f-80e5-10b2bddbed71.png)
![image](https://user-images.githubusercontent.com/93761101/229381119-718f29e6-cffe-476c-a022-cae04683beea.png)
![image](https://user-images.githubusercontent.com/93761101/229381124-549c3eb9-5e64-4650-807f-d3b8c1aa41aa.png)
