### ISSUE TITLE
Tìm hiểu và demo chức năng: Thêm trận đấu - Xóa trận đấu - Upload file json cho trận đấu

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#29]
- [x] Tìm hiểu chức năng Thêm trận đấu
- [x] Demo chức năng Thêm trận đấu
- [x] Tìm hiểu chức năng Xóa trận đấu
- [x] Demo chức năng Xóa trận đấu
- [ ] Tìm hiểu chức năng Upload file json cho trận đấu
- [ ] Demo chức năng Upload file json cho trận đấu

**Comment by anhhoang29** [comment]
Chức năng xóa trận đấu
![image](https://user-images.githubusercontent.com/93761101/230779882-de2507b5-828b-4fbe-9e60-55cfee7e0e76.png)
![image](https://user-images.githubusercontent.com/93761101/230779885-72c2935f-9c89-4423-b3d9-70873e299075.png)

**Comment by hautran-02** [comment]
chức năng thêm trận đấu:
![image](https://user-images.githubusercontent.com/110884738/230892935-74c6ad3a-3c5a-4040-8773-074e757a7320.png)
