### ISSUE TITLE
Tìm hiểu các chức năng của project

### ISSUE THREAD

**Issue by PhamNguyenNhutTruong** [PhamNguyenNhutTruong/Nhom2_CCPTPM#3]

**Comment by PhamNguyenNhutTruong** [comment]
Hoàn thành tìm hiểu các chức năng sau đây của project sẵn có:
- Ghép Highlight lại với nhau
- Hủy ghép Highlight 
- Merge các Highlight lại với nhau
- Cho phép download video
- Cho phép share video
- Update các thông tin liên qua đến nội dung video

**Comment by anhhoang29** [comment]
- Lấy( Thông tin) các trận đấu
- Thêm trận đấu vào danh sách quản lý
- Xóa trận đấu khỏi danh sách quản lý dựa trên ID
- Xóa Highlight khỏi danh sách quản lý dựa trên ID
- Lấy tất cả Highlight có trong danh sách quản lý
- Lấy Highlight của trận đấu dựa vào ID của trận đấu

**Comment by hautran-02** [comment]
**Hoàn thành tìm hiểu các chức năng sau đây của project sẵn có:**
- Sign in
- Sign up
- Lấy thông tin các giải đấu
- Thêm thông tin các giải đấu vào danh sách quản lý
- Lấy( Thông tin) trận đấu dựa vào ID

**Comment by PhamNguyenNhutTruong** [comment]
Đã hoàn thành việc tìm hiểu các chức năng đã có của proeject
