### ISSUE TITLE
Thực hiện tìm hiểu và demo chức năng: Lọc thông tin trận đấu - Tìm kiếm trận đấu - Xử lý đánh dấu để cắt ghép video

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#30]
- [x] Tìm hiểu chức năng Lọc thông tin trận đấu 
- [x] Demo chức năng Lọc thông tin trận đấu 
- [x] Tìm hiểu chức năng Tìm kiếm trận đấu
- [x] Demo chức năng Tìm kiếm trận đấu
- [x] Tìm hiểu chức năng Xử lý đánh dấu để cắt ghép video
- [ ] Demo chức năng Xử lý đánh dấu để cắt ghép video

**Comment by anhhoang29** [comment]
Tìm kiếm trận đấu
![image](https://user-images.githubusercontent.com/93761101/230779917-e60d1f4f-8767-4461-94bc-ea2e098f0f2c.png)
![image](https://user-images.githubusercontent.com/93761101/230779935-5d96bef1-97b6-4e7b-b088-4194f4bc623c.png)

**Comment by hautran-02** [comment]
Lọc trấn đấu:
![image](https://user-images.githubusercontent.com/110884738/230891167-4526cdc6-1538-40ee-9a8a-0bb9f306d5a9.png)
