### ISSUE TITLE
Thực hiện tìm hiểu và demo chức năng: Upload hình ảnh, video - Xóa hình ảnh, video - Thêm hình ảnh vào video

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#31]
- [x] Tìm hiểu chức năng Upload hình ảnh, video
- [x] Demo chức năng Upload hình ảnh, video

- [x] Tìm hiểu chức năng Xóa hình ảnh, video
- [x] Demo chức năng Xóa hình ảnh, video

- [x] Tìm hiểu chức năng Thêm hình ảnh vào video
- [x] Demo chức năng Thêm hình ảnh vào video

**Comment by PhamNguyenNhutTruong** [comment]
**Chức năng thêm hình ảnh vào video**
_Upload ảnh_

![Image](https://user-images.githubusercontent.com/89334096/230763788-ad060347-70b1-4a41-8f4e-2bc5c037ea2b.png)



![Image](https://user-images.githubusercontent.com/89334096/230763967-c23c8e89-cdea-466b-b948-f3c26469b6eb.png)



![Image](https://user-images.githubusercontent.com/89334096/230764153-c6511826-7f08-42bd-961d-dd15910b2cb6.png)



![Image](https://user-images.githubusercontent.com/89334096/230764322-c863e2b8-5b33-4c2a-90b2-6e1282e8d754.png)



![Image](https://user-images.githubusercontent.com/89334096/230764335-484b7e5e-0534-49cb-b974-b8dc47c83539.png)

_Upload video_


![Image](https://user-images.githubusercontent.com/89334096/230764379-2b32c5a5-1873-4b5a-864f-2a1954dddd53.png)



![Image](https://user-images.githubusercontent.com/89334096/230764417-e7c1ae37-7ec4-4a9c-9469-90eec3bbf9f6.png)



![Image](https://user-images.githubusercontent.com/89334096/230764436-fb0d62cb-cb3f-4b06-83c2-316f13075e6c.png)

**Comment by anhhoang29** [comment]
Xóa hình ảnh và video
![image](https://user-images.githubusercontent.com/93761101/230779979-617704b3-aefa-495a-85c5-4e40ef1fa564.png)
![image](https://user-images.githubusercontent.com/93761101/230779984-0a9a76f2-e8ef-487d-aaa3-2d72801d8890.png)

**Comment by hautran-02** [comment]
chức năng Upload hình ảnh, video:
![image](https://user-images.githubusercontent.com/110884738/230892339-e6a56dcf-b752-4c75-9b6b-75a421d6b7f2.png)
