### ISSUE TITLE
Thực hiện tìm hiểu và demo chức năng: Thêm video khi xử lý video - Lọc, tìm kiếm video - Download video - Chia sẻ video

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#32]
- [x] Tìm hiểu chức năng Thêm video khi xử lý video
- [x] Demo chức năng Thêm video khi xử lý video

- [x] Tìm hiểu chức năng Lọc, tìm kiếm video
- [x] Demo chức năng Lọc, tìm kiếm video

- [x] Tìm hiểu chức năng Download video
- [x] Demo chức năng Download video

- [ ] Tìm hiểu chức năng Chia sẻ video
- [ ] Demo chức năng Chia sẻ video

**Comment by PhamNguyenNhutTruong** [comment]
**Chức năng download video**


![Image](https://user-images.githubusercontent.com/89334096/230763646-6ba02bd1-806a-4f51-a8ab-cff35c9f4129.png)



![Image](https://user-images.githubusercontent.com/89334096/230763657-fe75d146-68a6-49bd-be0e-7183beee1a98.png)



![Image](https://user-images.githubusercontent.com/89334096/230763665-819b424e-8f22-43e7-b0b0-6467507ddf0b.png)

**Comment by anhhoang29** [comment]
Lọc và tìm kiếm video
![image](https://user-images.githubusercontent.com/93761101/230780060-22cbf7d6-9afc-4905-b343-dc4e8aad0a5d.png)

**Comment by hautran-02** [comment]
chức năng thêm video khi xử lý video: 
![image](https://user-images.githubusercontent.com/110884738/230893521-28531b02-373e-44ff-87da-1b9c74bf306c.png)
