### ISSUE TITLE
Tìm hiểu và thực thi project trên AWS

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#33]
- [x]  Tìm hiểu AWS
- [ ] Thực thi project trên  AWS

**Comment by anhhoang29** [comment]
Tui đã tham gia lab của thầy Phụng, nhưng chưa thực thi
![image](https://user-images.githubusercontent.com/93761101/230730510-105c6c7e-1358-4ecf-ba22-32e5a986c55a.png)

**Comment by PhamNguyenNhutTruong** [comment]
![Image](https://user-images.githubusercontent.com/89334096/230765368-f68fb076-f0f3-4830-8486-317717109ba8.png)

**Comment by hautran-02** [comment]
![image](https://user-images.githubusercontent.com/110884738/230893038-22bc871d-065c-48a3-8ca6-c04f43c8a53f.png)
