### ISSUE TITLE
Tìm hiểu và thực hiện chức năng thêm thumbail cho video

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#35]

**Comment by PhamNguyenNhutTruong** [comment]
Thêm thumbnail vào video là một tính năng quan trọng trong quá trình tạo và chia sẻ video trên các nền tảng trực tuyến. Thumbnail là hình ảnh nhỏ được chọn để hiển thị trước khi người xem bắt đầu phát video. Nó giúp thu hút sự chú ý của người xem và tạo ra ấn tượng đầu tiên về nội dung của video.

**Demo thử chức năng - Còn lỗi**
![image](https://user-images.githubusercontent.com/89334096/231151913-b7e19f6a-7437-48d8-8283-c29fbb73f9fd.png)
