### ISSUE TITLE
Tiếp tục phát triên chức năng thêm thumbail ngày thứ 2

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#37]

**Comment by PhamNguyenNhutTruong** [comment]
Hiện vẫn còn gặp 2 lỗi sau: Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'System.Drawing.Size' to 'string'	DataVidsThumbnails	E:\PROJECT_CCPTPM\Thumbnail\CreateThumbnailsUsingFFMPEG\DataVidsThumbnails\Services\Concrete\ImageService.cs	85	Active **và**

![Image](https://user-images.githubusercontent.com/89334096/232231235-2a58d4d5-9f52-42f4-9d75-d1c8adbdf96d.png)
