### ISSUE TITLE
Làm chức năng forgot password

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#38]

**Comment by hautran-02** [comment]
Cần bổ sung chức năng Forgot password khi user quên mật khẩu.

**Comment by anhhoang29** [comment]
Sau khi tìm hiểu, nhóm nhận thấy project thiếu chức năng quên mật khẩu, vì vậy  nhóm đã kịp thời bổ sung chức năng

**Comment by PhamNguyenNhutTruong** [comment]
Project của nhóm mình phát triển còn thiếu đi chức năng forgot password. Điều này có thể gây ra một số vấn đề trong quá trình sử dụng. Ví dụ như  người dùng quên mật đi tài khoản của mình và họ không thể đăng nhập được vào hệ thống những không có gì để người dùng lấy lại tài khoản của mình. Do đó chức năng này rất cần thiết.
