### ISSUE TITLE
Phân tích chức năng forgot password

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#39]

**Comment by anhhoang29** [comment]
Chúc năng forgot sẽ cho phép chúng ta update password, sau khi người dùng lỡ quên mật khẩu cũ,
Người dùng sẽ nhập username, nếu khớp thì sẽ cho chúng ta update password,( vì một số hạn chế về công nghệ).

**Comment by PhamNguyenNhutTruong** [comment]
Tui có ý tưởng về đường đi của chức năng forgot password đó là: Tạo ra một đường dẫn nằm ở phần login cho phép dẫn tới giao diện của chức năng forgot password. Tại trang đó chúng ta sẽ yêu cầu người dùng nhập vào email/username, password, confirm password.
Khi đã nhập đầy đủ thông tin thì chúng ta sẽ thưc hiện logic như sau:
- Ở phía FE chúng ta sẽ kiểm tra xem password và confirm password có tuân theo các tiêu chí như là password và confirm password có chưa đầy đủ chữ hoa, chữ thường, số và kí tự đặc biệt hay không và password có giống với confirm password hay không. Nếu được thảo mãn thì đẩy thông tin xuống BE để tiến hành thay đổi mật khẩu. Nếu không thỏa thì hiển thị ra thông báo cho người dùng biết.
- Ở phía BE chúng ta sẽ nhận về thông tin và dùng thông tin đó(email/username) để kiểm tra xem tài khoản đó có tồn tại trong cơ sở dữ liệu hay không. Nếu có tiến hành cho đổi mật khẩu và xuất thông báo thành công. Nếu không tồn tài thì xuất ra thông báo thất bại.
