### ISSUE TITLE
Clone project

### ISSUE THREAD

**Issue by PhamNguyenNhutTruong** [PhamNguyenNhutTruong/Nhom2_CCPTPM#4]

**Comment by PhamNguyenNhutTruong** [comment]
Clone dự án về được nhưng gặp lỗi. Nên chỉ đẩy lên một folder tượng trưng.

**Comment by hautran-02** [comment]
Clone được Client nhưng vẫn chưa chạy được do bị conflict giữa các version của các package, cụ thể:
- Trong Package.json có một số package được gán phiên bản là "latest". Điều này có thể là nguyên nhân dẫn đến conflict.
