### ISSUE TITLE
Thiết kế giao diện Forgot Password

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#41]

**Comment by PhamNguyenNhutTruong** [comment]
ý tưởng về thiết kế giao diện Forgot password sẽ tương tự như giao diện của trang login những sẽ có thêm trường confirm password để sau khi người dùng nhập vào mật khẩu mới thì người dùng sẽ phải xác nhận lại mật khẩu đã nhập để đảm bảo rằng người dùng nhập đúng và nhớ chính xác mật khẩu vừa mới đặt lại.
![image](https://user-images.githubusercontent.com/89334096/234185408-b2fbfcfb-e763-4b0e-b5be-08d2f8fd0f79.png)

**Comment by anhhoang29** [comment]
Sau khi phân tích, nhóm đã lên ý tưởng về thiết kế giao diện Forgot password sẽ tương tự như giao diện của trang login những sẽ có thêm trường confirm password để sau khi người dùng nhập vào mật khẩu mới thì người dùng sẽ phải xác nhận lại mật khẩu đã nhập để đảm bảo rằng người dùng nhập đúng và nhớ chính xác mật khẩu vừa mới đặt lại.
- Thiết kết button forgot password
- Thêm các text box  
- Thêm button
