### ISSUE TITLE
Thiết kế logic cho Forgot Password

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#42]

**Comment by PhamNguyenNhutTruong** [comment]
ạo ra một đường dẫn nằm ở phần login cho phép dẫn tới giao diện của chức năng forgot password. Tại trang đó chúng ta sẽ yêu cầu người dùng nhập vào email/username, password, confirm password.
Khi đã nhập đầy đủ thông tin thì chúng ta sẽ thưc hiện logic như sau:

Ở phía FE chúng ta sẽ kiểm tra xem password và confirm password có tuân theo các tiêu chí như là password và confirm password có chưa đầy đủ chữ hoa, chữ thường, số và kí tự đặc biệt hay không và password có giống với confirm password hay không. Nếu được thảo mãn thì đẩy thông tin xuống BE để tiến hành thay đổi mật khẩu. Nếu không thỏa thì hiển thị ra thông báo cho người dùng biết.
Ở phía BE chúng ta sẽ nhận về thông tin và dùng thông tin đó(email/username) để kiểm tra xem tài khoản đó có tồn tại trong cơ sở dữ liệu hay không. Nếu có tiến hành cho đổi mật khẩu và xuất thông báo thành công. Nếu không tồn tài thì xuất ra thông báo thất bại.
