### ISSUE TITLE
Hoàn thành chức năng và demo forgot pasword

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#43]

**Comment by PhamNguyenNhutTruong** [comment]
**Phía FE**
![image](https://user-images.githubusercontent.com/89334096/234185858-ffd23375-df13-4f6e-a73f-1bcce17ed7f0.png)
![image](https://user-images.githubusercontent.com/89334096/234185795-9e55bbba-dd97-47db-b562-51fedf728327.png)
**Phía BE**
![image](https://user-images.githubusercontent.com/89334096/234185935-03f82952-2813-449f-8673-8a6a10f1404b.png)

**Comment by anhhoang29** [comment]
![image](https://user-images.githubusercontent.com/93761101/234239652-bed466dc-0f22-495c-95e9-0916e81ac1e7.png)
![image](https://user-images.githubusercontent.com/93761101/234239684-b2072096-6824-4a90-b4d0-64d14425986d.png)
