### ISSUE TITLE
Tìm hiểu docker compose

### ISSUE THREAD

**Issue by anhhoang29** [PhamNguyenNhutTruong/Nhom2_CCPTPM#44]

**Comment by anhhoang29** [comment]
Docker compose là một công cụ giúp định nghĩa và chạy multi-container trong những ứng dụng sử dụng Docker. Với Compose, chúng ta có thể config các services để phục vụ cho ứng dụng. Và tiện hơn khi chỉ với một câu lệnh, chúng ta có thể tạo và start tất cả các Docker containers services mà chúng ta sử dụng.
ứng dụng web 3 modules
Sử dụng 3 container riêng
mỗi modules chạy port khác nhau


=> docker compose là giải pháp cho vấn đề này


định dạng yaml
version: '3' 
services:
pg:
image: postgres:9.6-alpine
ports:
- 5432:5432
volumes:
- pgdata:/var/lib/postgresql/data
environment:
POSTGRES_DB: postgres 
POSTGRES_USER: postgres 
POSTGRES_PASSWORD: postgres
frontend:
image: Anhhoang2910/frontend:latest
build: 
context: .
volumes:
pgdata:

**Comment by PhamNguyenNhutTruong** [comment]
Docker Compose là một công cụ quản lý các container trong Docker. Nó cho phép định nghĩa và chạy các ứng dụng đa container với cấu hình môi trường được xác định trước. Các tệp cấu hình Docker Compose được viết bằng định dạng YAML, cho phép người dùng xác định các dịch vụ, mạng, tệp và các cài đặt khác. Khi được chạy, Docker Compose sẽ tạo ra một môi trường đa container được cấu hình theo tệp cấu hình, giúp cho việc triển khai và quản lý các ứng dụng Docker trở nên dễ dàng hơn.
Để sử dụng được Docker Compose, bạn có thể thực hiện các bước sau:
- Tạo một file docker-compose.yml trong thư mục của dự án.
- Định nghĩa các dịch vụ cần sử dụng trong file docker-compose.yml bằng cách sử dụng cú pháp YAML. Mỗi dịch vụ được định nghĩa bởi một service, có thể bao gồm các thuộc tính như image, ports, volumes,...
- Chạy lệnh docker-compose up để khởi chạy các dịch vụ.
Nếu muốn tắt các dịch vụ, bạn có thể sử dụng lệnh docker-compose down.
