### ISSUE TITLE
Tìm hiểu về React.

### ISSUE THREAD

**Issue by PhamNguyenNhutTruong** [PhamNguyenNhutTruong/Nhom2_CCPTPM#9]
- Tìm hiểu về luồng đi của project của nhóm.
- Cố gắng lấy được data hiện lên giao diện sử dụng.

**Comment by anhhoang29** [comment]
Các tính năng của reactjs

JSX: viết tắt của JavaScript extension, nó là React extension , giúp cho việc thay đổi cây DOM dễ dàng hơn bằng HTML-style code đơn giản. Nó là một trong những tính năng tốt và dễ sử dụng.
Components: Một trang web được xây dựng bằng ReactJS là một sự kết hợp nhiều component lại với nhau chứ không phải chung một Template như bình thường. Các component cũng như các hàm JavaScript bình thường, giúp tạo ra các code dễ dàng bằng cách tách các logic ra thành các đoạn code độc lập có thể tái sử dụng. Chúng ta có thể sử dụng component dưới dạng function hoặc class, ngoài ra các component còn có state và props.
Virtual DOM: ReactJS tạo một thứ gọi là Virtual DOM (DOM ảo). Đúng như tên gọi, nó là một copy của DOM thật trên trang web đó. ReactJS dùng những DOM ảo đó để tìm đúng những DOM thật cần được cập nhật khi có bất kỳ sự kiện nào làm các thành phần bên trong nó thay đổi.
Javascript Expressions: Biểu thức JS có thể sử dụng trong file .jsx hoặc .js bằng cách sử dụng cặp dấu ngoặc nhọn “{}”.

**Comment by hautran-02** [comment]
**Các kiến thức đã tìm hiểu:**
- ReactJS là một tài liệu về lập trình web bao gồm các chủ đề như hành vi mặc định của thẻ a, event listener, JSON, Promise, Fetch, Postman, ECMAScript 6, responsive design và grid system. Nó cũng đề cập đến ReactJS.
- ReactDOM là cầu nối giữa React Lib và DOM

**Comment by PhamNguyenNhutTruong** [comment]
Tìm hiểu được vể JSX và một số nguyên lý hoạt động cơ bản của React.
Tìm hiểu được props trong React:
- Trong ReactJS, Props là viết tắt của thuộc tính "Properties" - các thuộc tính được truyền vào component từ bên ngoài. Props là các đối tượng có chứa thông tin cần thiết để hiển thị cho component, và không thể thay đổi giá trị bên trong component.
- Các Props được định nghĩa trong component khi khai báo function component hoặc class component, và có thể truyền vào thông qua cú pháp props hoặc được phân rã bằng cú pháp ...props. Khi định nghĩa Props, ta có thể định nghĩa kiểu dữ liệu của các Props để kiểm tra tính hợp lệ và giúp IDE tự động gợi ý các thuộc tính cần truyền vào cho component.
- Props được sử dụng để truyền dữ liệu giữa các component, từ component cha tới component con thông qua việc truyền Props từ component cha sang component con. Props cũng được sử dụng để cấu hình các component, cho phép tùy chỉnh hành vi hoặc nội dung của component.
